name: Build and Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Setup V
      uses: prantlf/setup-v-action@v2
    - name: Build and Test
      run: make RELEASE=1
    - name: Shelve output
      uses: prantlf/shelve-output-action@v2

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Setup V
      uses: prantlf/setup-v-action@v2
    - name: Build and Test
      run: make RELEASE=1
    - name: Shelve output
      uses: prantlf/shelve-output-action@v2

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout Sources
  #     uses: actions/checkout@v4
  #   - name: Setup V
  #     uses: prantlf/setup-v-action@v2
  #   - name: Build
  #     run: cmd /c make-exe.bat
  #   - name: Shelve output
  #     uses: prantlf/shelve-output-action@v2

  release:
    if: github.ref_name == 'master'
    needs:
      - linux
      - macos
      # - windows
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Unshelve output
      uses: prantlf/unshelve-output-action@v2
      with:
        include-windows: false
    - name: Discard shelf
      uses: prantlf/discard-shelf-action@v3
      with:
        include-windows: false
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: '*.zip'
