name: Build and Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:
  windows-cross:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: prantlf/setup-v-action@v4
    - run: sudo apt-get install gcc-mingw-w64-x86-64
    - run: make build RELEASE=1 WINDOWS=1
    - if: ${{ needs.macos.outputs.changed == 'true' }}
      uses: prantlf/shelve-output-action@v4
      with:
        os: windows
